#ifndef SHADER_SERIALIZER_GLOBAL_H
#define SHADER_SERIALIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHADER_SERIALIZER_LIBRARY)
#  define SHADER_SERIALIZER_EXPORT Q_DECL_EXPORT
#else
#  define SHADER_SERIALIZER_EXPORT Q_DECL_IMPORT
#endif

#endif // SHADER_SERIALIZER_GLOBAL_H
